INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you blowing a kiss', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your outfit on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a voice note saying something sexy', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Do a slow spin for me on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your lips', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you dance on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you winking', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Bite your lip for me on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your eyes', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your smile on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you laughing', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Blow me a kiss on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your hands', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your hair down on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you saying my name', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Lick your lips on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your neck', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your favorite pose on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you stretching', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Whisper something to me on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your collarbone', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you apply lipstick on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you twirling', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Run your fingers through your hair on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your shoulders', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your best seductive look on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you biting your finger', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Trace your lips with your finger on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your back', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you relax on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you in your favorite outfit', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Touch your neck slowly on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your legs', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your bedroom on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you lying down', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Suck on your finger on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your thighs', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you sit seductively on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you in bed', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Caress your arm on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your stomach', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your pajamas on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you yawning', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Touch your chest lightly on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your hips', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you wake up on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you stretching in bed', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Run your hand down your side on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your waist', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your morning look on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you under the covers', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Touch your thigh on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your curves', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get comfortable on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you in a towel', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Caress your leg on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your silhouette', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your night routine on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you getting cozy', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Touch your lower back on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo from behind', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you lounge on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you in lingerie', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Run your hands over your body on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your cleavage', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your underwear on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you teasing', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Touch yourself over clothes on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your bra', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you undress slowly on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you in a bra', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Squeeze your thighs together on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your panties', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your body on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you posing', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Arch your back on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your ass', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you move your hips on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you twerking', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Grab your ass on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your chest', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your best angle on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you bending over', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Touch your breasts over clothes on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your nipples through shirt', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you touch yourself over clothes on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you grinding on a pillow', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Moan softly on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo teasing your underwear off', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how turned on you are on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you moaning my name', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Squeeze your breasts on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you topless from behind', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you play with your hair seductively on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you taking off your shirt', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Rub your thighs together on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you in just panties', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your O face on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you breathing heavily', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Spank yourself lightly on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your hand between your legs', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how wet you are getting on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you saying dirty things', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Touch yourself and show me your face on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you completely naked', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me your full body nude on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you playing with your nipples', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Tell me what you want me to do to you on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you spread open', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you pleasure yourself on video', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you masturbating for 1 minute', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Finger yourself on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your pussy', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you cum on video call', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you orgasming', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Make yourself cum while I watch on camera', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you sucking on a dildo', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you ride a pillow on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you using a vibrator', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Masturbate for me on video call for 5 minutes', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with a toy inside', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how deep you can take a dildo on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you fingering your ass', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Edge yourself 3 times on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you squirting', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck yourself on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your wet pussy', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Deepthroat a dildo for me on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you spanking yourself', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you play with your clit on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you moaning loudly', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Use a butt plug on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with cum on you', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you taste yourself on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you cumming hard', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself with a dildo on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you begging to cum', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you choke yourself on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your asshole', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Ride a dildo for me on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you with nipple clamps', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you gag on a toy on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you drooling', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Slap your pussy on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with a collar on', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck your ass on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you with two toys', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Cum multiple times on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you screaming my name', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how rough you can be with yourself on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your holes filled', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in the shower on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you tasting your cum', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you edge for 10 minutes on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you with a gag in', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Spank yourself until red on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your marks', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you use a wand on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you anal training', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself thinking of me on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you shaking from orgasm', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you torture your nipples on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you bound', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Ride a dildo reverse on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you using ice', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you double penetrate yourself on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you crying from pleasure', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself on all fours on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your dripping pussy', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you use a suction toy on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you with hot wax', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Cum on command on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you begging me to let you cum', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck yourself standing on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with a leash', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Ride a dildo until you squirt on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you with clamps on', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fist yourself on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you gagging and drooling', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck your throat with a dildo on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you covered in your juices', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you use a fuck machine on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you with multiple orgasms', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in public bathroom on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being loud', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you punish yourself on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with rope marks', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Ride a dildo in the mirror on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you using a paddle', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you stretch yourself on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you losing control', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself with the biggest toy you have on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you gaping', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you use a dildo and vibrator together on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you with a remote control toy in public', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Cum while standing on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you convulsing', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you ruin your orgasm on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you exhausted from cumming', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself until you cannot take it on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you with a huge dildo', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you overstimulate yourself on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you squirting everywhere', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck your ass and pussy at the same time on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your destroyed holes', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you make yourself scream on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you cumming back to back', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in a risky place on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being filthy', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you degrade yourself on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you at your dirtiest', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Ride a dildo and tell me you are mine on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you worshipping a dildo', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you submit on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you calling me daddy', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself and beg for me on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you on your knees', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you pleasure yourself for me on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you saying you belong to me', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Cum while saying my name on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you thanking me for letting you cum', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you worship me on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you marked as mine', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself and tell me who you belong to on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being my good girl', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how obedient you are on video', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you asking permission to cum', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself only when I tell you on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo proving you are mine', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you serve me on video call', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being my slut', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Cum only when I allow you on camera', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you fucking yourself in a public bathroom', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck yourself at work on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you masturbating in your car', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in a changing room and send video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with a toy in public', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you cum in a risky place on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you fucking yourself outside', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Wear a remote vibrator and let me control it on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you cumming in public', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself on a balcony on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you flashing in public', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck yourself with people nearby on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you naked in a public place', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in a parking lot on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being reckless', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you edge in public on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you exposed somewhere risky', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself at a friends house on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you with no panties in public', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you cum while someone could catch you on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being a slut in public', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in a store bathroom on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you touching yourself in public', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck yourself at a party on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you masturbating with people around', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in a library on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being wild', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you cum in your office on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you naked at work', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself on public transport on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you flashing strangers', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck yourself in a park on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being shameless', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in a restaurant bathroom on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with cum on you in public', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you squirt somewhere risky on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being a whore', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while driving on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you losing all control', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck yourself at the gym on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you spread in public', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in a hotel hallway on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being absolutely filthy', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you cum at the beach on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being used', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself in an elevator on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with someone elses cum', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you fuck yourself with a stranger nearby on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you sucking someone off', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while someone watches on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you with another person', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get fucked by someone else on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you covered in cum', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself and let someone join on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being shared', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you take two dicks on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you in a threesome', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while giving head on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with multiple people', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get gangbanged on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being a cum dump', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while others use you on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being passed around', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you service multiple people on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you destroyed by others', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being recorded by others on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you at an orgy', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get used by strangers on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being a party favor', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while others watch and film on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you being degraded', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you submit to others on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being dominated', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being humiliated on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being owned', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get bred on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of cum dripping out of you', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself after being filled on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being a breeding slut', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you take loads on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you begging to be bred', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself with cum as lube on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you leaking', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you clean up cum on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you licking cum off yourself', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself covered in cum on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you snowballing', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you worship cock on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you on your knees for someone', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while deepthroating on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you gagging on dick', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you take a facial on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you swallowing', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while sucking balls on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of cum on your face', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you beg for cum on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being a cum slut', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while getting throat fucked on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you choking on cock', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get your face fucked on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with dick in your mouth', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being spit on on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being degraded sexually', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get slapped around on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being choked', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being spanked hard on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your bruises', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get punished on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being whipped', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being tortured on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you crying from pain', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you take rough treatment on video', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you marked up', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being abused on camera', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being destroyed', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get wrecked on video call', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being absolutely ruined', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself at a sex party', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you fucking a stranger', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get gangbanged live on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you at a glory hole', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while others fuck you on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being airtight', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you service an entire room on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you at a swingers club', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself being used by multiple people', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you covered in multiple loads', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being filmed by strangers on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being the entertainment', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get passed around on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you in a train', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself being bred by strangers', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you at a bukkake', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while taking loads on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being a public cum dump', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get used at a party on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you fucking for money', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself being a prostitute', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with a client', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while selling your body on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being paid for sex', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you whore yourself out on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you on the street corner', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself picking up strangers', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you in a brothel', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while working on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you with multiple clients', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you service anyone who pays on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being a hooker', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself doing anything for money', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you degraded for cash', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being pimped on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being sold', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get auctioned off on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being rented out', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself being traded', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you being owned by others', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being property on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being livestock', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you get treated like meat on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being objectified', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself as a sex object', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you being dehumanized', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being a thing on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being furniture', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you serve as an object on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being a toilet', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself being degraded completely', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you at your lowest', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being humiliated publicly on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you with no dignity', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you debase yourself on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being pathetic', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself begging for abuse', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you broken', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while crying on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you destroyed mentally', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you lose yourself on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you at rock bottom', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself doing the unthinkable', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with no limits', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while crossing every line on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being absolutely depraved', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how far you will go on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you doing the forbidden', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself being completely shameless', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with no boundaries', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being filmed for the world on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you going viral', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you become internet famous on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you on pornhub', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself on onlyfans', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you on a porn site', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while streaming publicly on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you being a porn star', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you perform for thousands on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you in professional porn', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself shooting content', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you on set', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while being directed on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you in a scene', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you act for the camera on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being a professional slut', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself making content with others', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with porn stars', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while collaborating on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you in a collab', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you work with others on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you at an industry party', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself networking', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you with famous people', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while building your brand on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you promoting yourself', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you market yourself on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you selling yourself', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself advertising', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your promotional material', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while growing your following on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you gaining subscribers', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you engage your audience on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you responding to fans', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself taking requests', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of you doing customs', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while fulfilling orders on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you making money', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you cash in on video call', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you counting your earnings', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself getting paid', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a photo of your bank account', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Fuck yourself while making bank on camera', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a clip of you living your best life', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Show me how you profit from your body on video', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Send me a video of you being successful', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'dare', 'Livestream yourself thriving', 'drunk');
