INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What was your first thought when you saw me tonight?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way I touch you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'When did you first want to kiss me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What outfit of mine drives you crazy?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite physical feature of mine?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What song makes you think of us?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite memory of us?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What do you find most attractive about me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing I do in bed?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'When do you feel most connected to me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite date we have been on?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What part of my body do you love most?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to cuddle with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about our chemistry?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What makes you want me most?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way I kiss you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What do you love most about my personality?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite intimate moment we have shared?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my smile?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite scent on me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my voice?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to wake up with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my eyes?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite romantic gesture I have done?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my laugh?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite place to be touched by me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my hands?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way I show you affection?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my lips?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite time of day with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my body?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to relax with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my energy?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite compliment I have given you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my confidence?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to fall asleep with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my style?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite inside joke we have?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my passion?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite photo of us together?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my sense of humor?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way I make you feel special?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my hair?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite adventure we have had?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my neck?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite meal we have shared?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my intelligence?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way I surprise you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my back?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite drink to share with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my shoulders?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite place we have been together?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my legs?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to spend a night in with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my arms?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite movie to watch with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my chest?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite gift I have given you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my stomach?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite season to spend with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my hips?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way I make you laugh?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my thighs?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite vacation spot with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my butt?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to hold me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my skin?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite restaurant to go to with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my curves?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite pet name I call you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my muscles?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way I comfort you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my jawline?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite holiday to celebrate with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my collarbone?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite activity to do with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my waist?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to dance with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my figure?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite song to listen to with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my physique?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to be close to me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my silhouette?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite dessert to share with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my presence?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to kiss me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my aura?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite cocktail to drink with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my vibe?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to tease me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my magnetism?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite bar to go to with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my allure?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to flirt with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my charm?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite club to dance at with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my sex appeal?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to seduce me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my sensuality?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite party we have been to together?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my sexuality?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to touch me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my desire?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite concert we have been to?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my lust?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to please me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my passion for you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite festival to attend with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my hunger for you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to turn me on?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my craving for you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite road trip we have taken?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my need for you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to get me excited?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my want for you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite weekend getaway with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my yearning for you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to make me smile?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my devotion to you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite brunch spot with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my loyalty to you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to make me blush?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my commitment to you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your dirtiest fantasy about me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever touched yourself thinking about me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the kinkiest thing you want to try with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Where is the riskiest place you want to have sex with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What turns you on most about my body?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had a sex dream about me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite position with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is something sexual you are too shy to ask for?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'When did you first want to sleep with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your biggest turn on during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever fantasized about me with someone else?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing I have ever done to you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about our sex life?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is something you wish we did more in bed?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever gotten off to a photo of me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your secret sexual desire?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the naughtiest thing you have thought about doing to me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer giving or receiving oral?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to be dominated?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite way to dominate?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever faked an orgasm with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most adventurous sexual thing you want to try?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite part of foreplay?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever been jealous watching me talk to someone?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest text I have ever sent you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing I do with my tongue?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you like it rough or gentle?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the longest you have gone without thinking about sex with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing I do with my hands?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to have sex with me in public?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest thing you have ever said to me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my moans?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you like being teased or going straight to it?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest outfit you have seen me in?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever thought about recording us?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my kisses during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is something you are curious about trying sexually?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most turned on you have ever been by me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer morning sex or night sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing I whisper to you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to tie me up?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my confidence?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite memory of us being intimate?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you like dirty talk or quiet sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the naughtiest place we have had sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I smell during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be watched by me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing I could wear to bed?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my body during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer slow and sensual or fast and hard?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most spontaneous sexual thing we have done?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my touch?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to use toys with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my vulnerability?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about our chemistry in bed?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you like eye contact during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing I have ever whispered to you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my reactions during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to role play with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my aggression?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I move?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer lights on or lights off?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most intense orgasm you have had with me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about my stamina?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to blindfold me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my submission?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the sounds I make?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer shower sex or bed sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing about my dominance?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I taste?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to spank me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my neediness?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I grip you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer quickies or long sessions?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing about my begging?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I finish?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be spanked by me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my control?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I breathe?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer being on top or bottom?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing about my desperation?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I climax?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to pull my hair?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my intensity?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I surrender?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer one round or multiple rounds?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing about my vulnerability in bed?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I take control?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted your hair pulled by me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my rawness?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I let go?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer sex with music or silence?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing about my primal side?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I respond to you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to bite me during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my wild side?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I crave you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer sex after drinking or sober?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing about my animalistic side?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I need you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be bitten by me during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my uninhibited side?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I worship you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer sex in the morning or after a night out?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing about my unfiltered desire?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I devour you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to scratch me during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my uncontrolled passion?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I consume you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Do you prefer sex with or without alcohol?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the hottest thing about my unbridled lust?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I possess you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be scratched by me during sex?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sexiest thing about my savage side?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your favorite thing about the way I claim you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the filthiest thing you want me to do to you right now?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever masturbated in a public place thinking of me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your darkest sexual fantasy involving me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me watch you pleasure yourself?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most degrading thing you want me to do to you?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever fantasized about a threesome with me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest place you want to fuck me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me tie you up and use you?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most taboo sexual desire?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever gotten off to porn thinking it was us?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest thing you have ever imagined doing to me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me record us having sex?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most shameful turn on?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to fuck me in front of someone?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the kinkiest role play scenario you want to try?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me dominate you completely?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most perverted thought about me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever sent nudes to someone else while with me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most extreme thing you want to try sexually?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me choke you during sex?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your deepest sexual secret?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever fantasized about being used by me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the sluttiest thing you have ever done?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me share you with someone else?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most depraved sexual urge?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be my sex slave?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the freakiest thing you want me to do to your body?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me use toys on you in public?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most forbidden fantasy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever cheated on me in your mind?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you have ever said during sex?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me fuck you anywhere I want?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most twisted sexual thought?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be punished by me sexually?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest thing you want me to call you?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me control your orgasms?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most sinful desire?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever fantasized about being owned by me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the raunchiest thing you want to experience?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me edge you until you beg?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most obscene sexual craving?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be degraded by me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the filthiest place you have touched yourself?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me use you however I want?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most vulgar fantasy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to worship my body?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the kinkiest toy you want to use on me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me mark you as mine?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most lewd thought about us?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be bred by me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you want in your mouth?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me deny you pleasure?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most indecent sexual wish?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be my personal toy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest position you want to try?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me fuck you in front of a mirror?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most shameless turn on?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be collared by me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the freakiest thing you want me to whisper?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me take complete control of your body?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most explicit fantasy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be restrained by me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you want me to lick?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me make you scream my name?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most carnal desire?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be blindfolded and used?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the filthiest thing you want me to taste?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me ruin you for anyone else?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most primal urge with me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be gagged during sex?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest thing you want me to suck?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me make you cum until you cry?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most animalistic craving?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be spanked until you are red?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you want me to bite?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me fuck you until you cannot walk?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most savage sexual need?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be choked until you see stars?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the filthiest thing you want me to grab?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me breed you over and over?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most feral desire?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted your hair pulled until it hurts?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest thing you want me to squeeze?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me use your body all night?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most untamed fantasy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be slapped during sex?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you want me to stroke?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me make you my personal slut?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most raw sexual impulse?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be pinned down and taken?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the filthiest thing you want me to penetrate?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me fuck you in every room of the house?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most unhinged sexual thought?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be thrown around during sex?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest thing you want me to fill?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me claim every inch of you?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most uncontrolled lust?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be bent over and pounded?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you want me to stretch?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me make you addicted to me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most unbridled passion?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be held down and ravaged?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the filthiest thing you want me to pound?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me make you beg for more?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most insatiable craving?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be dominated until you submit completely?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest thing you want me to destroy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me fuck you until you forget your own name?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most voracious sexual appetite?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be used until you are completely spent?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you want me to wreck?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me make you mine in every way possible?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most ravenous desire for me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever wanted to be taken so hard you lose control?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the filthiest thing you want me to own about you?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me push you past every limit you have?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'If we were not together, who in this room would you fuck?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the craziest place you have ever had sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had a sex dream about my friend?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you ever have a threesome with me and who?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the weirdest thing that has turned you on?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever hooked up with someone in this room?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your body count and am I the best?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me watch you with someone else?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most illegal place you have had sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever fantasized about my sibling?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the drunkest you have been during sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you fuck me right now in front of everyone?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most people you have slept with in one week?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever sent nudes to the wrong person?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most embarrassing sexual moment?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me fuck your best friend?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you have ever done drunk?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever cheated and not told anyone?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the biggest dick or tightest pussy you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you do an orgy with me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most fucked up porn you have watched?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever fucked someone for money or gifts?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is your most shameful hookup story?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me film us and post it online?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the grossest thing you have done sexually?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever fucked someone you hated?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the quickest you have ever came?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you fuck a celebrity in front of me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the longest you have gone without showering after sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with multiple people in one day?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most public place you have gotten head?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let strangers watch us fuck?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the worst sex you have ever had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever lied about your body count?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most times you have came in one session?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you join a sex cult with me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most desperate thing you have done for sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever fucked someone to make me jealous?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the weirdest fetish you have tried?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me pimp you out?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most regrettable person you have slept with?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex while someone else was in the room?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the dirtiest thing you have said during sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you fuck me for money right now?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most painful sexual experience you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever walked in on your parents?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most embarrassing thing that happened during sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me sell our sex tape?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the nastiest thing you have tasted?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with a coworker?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most times you have had sex in one day?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you fuck someone for a million dollars in front of me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most awkward sexual encounter you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex at work?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the weirdest place you have masturbated?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me auction off your virginity if you still had it?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most disgusting thing you have done for pleasure?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone way older or younger?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most fucked up thing you have masturbated to?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you participate in a gangbang?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most illegal sexual thing you have done?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone related to me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most people you would fuck at once?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me watch you fuck my friend?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most depraved thing you have witnessed?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex while high on drugs?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most humiliating sexual experience you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you fuck a stranger for me to watch?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most taboo thing you have fantasized about?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex in a church or sacred place?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most times you have orgasmed in one day?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me prostitute you for a night?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most shameful thing you have done sexually?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone famous?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most dangerous sexual situation you have been in?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you fuck someone I hate if I asked you to?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most perverted thing you have done alone?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with multiple partners without them knowing?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most extreme porn category you have watched?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me share you with my friends?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most unprotected sex you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone you just met?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most degrading thing you have done for sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you participate in a sex party with me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most unsanitary place you have had sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone for revenge?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most animalistic sex you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me trade you for someone else for a night?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most violent sexual encounter you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex while someone watched without knowing?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most degenerate thing you have participated in?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you fuck everyone in this room if I told you to?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most intoxicated you have been during sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone in a relationship?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most morally wrong sexual thing you have done?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me whore you out to my enemies?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most reckless sexual decision you have made?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone you should not have?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most savage thing you have done in bed?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me use you as a sex toy for others?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most unhinged sexual experience you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex in front of your parents house?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most feral thing you have done sexually?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me rent you out for sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most chaotic sexual situation you have been in?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone twice your age?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most uncontrolled sexual moment you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me give you to someone as a gift?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most primal sexual urge you have acted on?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone you met online immediately?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most wild sexual adventure you have had?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me bet you in a poker game?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most insane thing you have done while horny?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Have you ever had sex with someone whose name you did not know?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most out of control you have been sexually?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'Would you let me loan you out to strangers?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('truth-or-dare', 'truth', 'What is the most absolutely deranged sexual thing you have done?', 'drunk');
