INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather kiss me in the rain or under the stars?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather hold hands everywhere or cuddle all the time?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a romantic dinner or a fun adventure date?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather receive flowers or chocolates from me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather dance with me or sing to me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have breakfast in bed or a midnight snack together?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch the sunrise or sunset with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather get a massage from me or give me one?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a beach vacation or mountain getaway with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather cook together or order takeout?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a movie night or game night?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather slow dance or dirty dance with me?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a picnic or a fancy restaurant date?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather get matching tattoos or matching jewelry?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a long passionate kiss or many quick kisses?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather shower together or take a bath together?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have me whisper or talk dirty to you?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather make out in public or in private?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a spontaneous date or a planned one?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather receive a love letter or a sexy text?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be teased all day or satisfied immediately?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have morning sex or night sex?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be on top or bottom?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have slow sensual sex or fast rough sex?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with the lights on or off?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather give oral or receive oral?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a quickie or a long session?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the shower or in bed?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be kissed on the neck or the lips?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have me pull your hair or scratch your back?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with music or in silence?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be dominated or dominate?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have foreplay for an hour or skip to sex?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the car or outdoors?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather send nudes or receive nudes?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex after drinking or sober?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have one round or multiple rounds?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be blindfolded or handcuffed?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on the couch or the floor?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be spanked or choked lightly?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the morning or afternoon?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch porn together or make our own?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a hotel or at home?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather use toys or just our bodies?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex standing up or lying down?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be loud or quiet during sex?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with eye contact or not?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the pool or hot tub?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be bitten or licked?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with candles or regular lights?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on a weekend or weekday?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex before or after a workout?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in summer or winter?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in lingerie or naked?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on silk sheets or regular sheets?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex after a date or randomly?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me on top or from behind?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with the windows open or closed?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the dark or with dim lighting?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in heels or barefoot?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on vacation or at home?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a dress or pants?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me freshly showered or natural?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in makeup or without?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me with hair up or down?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on a soft bed or firm surface?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in stockings or bare legs?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a bra or topless?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in panties or commando?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a skirt or shorts?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a thong or boyshorts?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in lace or silk?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in red or black lingerie?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a bodysuit or bra and panties?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a corset or babydoll?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a robe or nightgown?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in your shirt or mine?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in socks or barefoot?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a bikini or one piece?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a crop top or tank top?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in jeans or leggings?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a tight dress or loose dress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a mini skirt or maxi skirt?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a button up or t-shirt?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a sweater or hoodie?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a sports bra or regular bra?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in yoga pants or sweatpants?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a romper or jumpsuit?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a halter top or strapless top?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a v-neck or crew neck?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a blazer or cardigan?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a pencil skirt or flowy skirt?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a tube top or off shoulder top?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a bodycon dress or A-line dress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a wrap dress or shift dress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a slip dress or sundress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a maxi dress or midi dress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a cocktail dress or casual dress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a backless dress or low cut dress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a sheer top or solid top?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a mesh top or regular top?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a cutout dress or regular dress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a slit dress or no slit?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a one shoulder dress or two straps?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a sequin dress or plain dress?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in a leather jacket or denim jacket?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in boots or sneakers?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in sandals or flats?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in stilettos or wedges?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in pumps or platforms?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in ankle boots or knee high boots?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in thigh high boots or regular boots?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in strappy heels or closed toe heels?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in peep toe heels or pointed toe heels?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in block heels or stiletto heels?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in kitten heels or high heels?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in mules or slides?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in espadrilles or loafers?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in oxfords or brogues?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me in combat boots or chelsea boots?', 'baby');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have rough sex or make love?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be tied up or tie me up?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in public or get caught at home?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather use handcuffs or rope?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be spanked with a hand or a paddle?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have anal sex or try a threesome?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch me masturbate or have me watch you?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with a stranger watching or record it?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be choked during sex or have your hair pulled?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather use a vibrator or a dildo on me?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a car or in the woods?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be blindfolded and teased or edged for an hour?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on the kitchen counter or the dining table?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex against the wall or on the stairs?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the bathroom or the closet?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the laundry room or the garage?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on the balcony or in the backyard?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the basement or the attic?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a public bathroom or a changing room?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in an elevator or a stairwell?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a parking lot or an alley?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex at the beach or in the ocean?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a tent or under the stars?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a movie theater or a library?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex at a party or at work?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a club bathroom or a bar bathroom?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a restaurant bathroom or a store bathroom?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a gym or a sauna?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a pool or a jacuzzi?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on a boat or on a plane?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on a train or on a bus?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a taxi or an Uber?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a limo or a regular car?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a hotel room or an Airbnb?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a fancy hotel or a cheap motel?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a penthouse or a cabin?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a mansion or a tiny house?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a castle or a treehouse?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a cave or on a mountain?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a field or a forest?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in a desert or a jungle?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex in the snow or in the rain?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex during a thunderstorm or a heatwave?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex at sunrise or at midnight?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex during the day or at night?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on a Monday or a Friday?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on your birthday or mine?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on Christmas or New Years?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on Valentines Day or our anniversary?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex on Halloween or Thanksgiving?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex sober or drunk?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex high or on molly?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex after smoking or after drinking?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me tipsy or completely wasted?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me on edibles or on shrooms?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me on coke or on acid?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me on pills or on powder?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me buzzed or faded?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me crossfaded or rolling?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a joint or after shots?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after wine or after beer?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after tequila or after vodka?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after whiskey or after rum?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after champagne or after cocktails?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a blunt or after a bong?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a dab or after a vape?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after indica or after sativa?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a body shot or after a keg stand?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after beer pong or after flip cup?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a party or after a club?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a rave or after a concert?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a festival or after a bar?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a wedding or after a funeral?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after a graduation or after a promotion?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after winning or after losing?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me after good news or after bad news?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me when happy or when sad?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me when angry or when calm?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me when stressed or when relaxed?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me when tired or when energized?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me when horny or when not?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me when we fight or when we make up?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me spontaneously or planned?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me passionately or aggressively?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me romantically or dirty?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me lovingly or roughly?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me gently or hard?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me slowly or fast?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me softly or intensely?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me sweetly or wildly?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me tenderly or violently?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me carefully or carelessly?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me quietly or loudly?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me silently or vocally?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me moaning or screaming?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me whispering or talking dirty?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me begging or commanding?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me submitting or dominating?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me obeying or controlling?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me following or leading?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me serving or being served?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me pleasing or being pleased?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me giving or receiving?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me taking or being taken?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me using or being used?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me owning or being owned?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me claiming or being claimed?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me marking or being marked?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me branding or being branded?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me collaring or being collared?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me leashing or being leashed?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me binding or being bound?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me restraining or being restrained?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me tying or being tied?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me cuffing or being cuffed?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me gagging or being gagged?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with me blindfolding or being blindfolded?', 'medium');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a threesome with another girl or another guy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch me fuck someone else or have someone watch us?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have an orgy or a gangbang?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be shared or share me?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex at a sex party or a swingers club?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck me in front of strangers or friends?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be filmed having sex or livestream it?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather post our sex tape or sell it?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex for money or for fame?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a porn star or a prostitute?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a celebrity or fuck me in front of one?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with my best friend or your best friend?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with my sibling or my parent?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with your ex or my ex?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather cheat on me or have me cheat on you?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have an open relationship or a polyamorous one?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather let me sleep with others or sleep with others yourself?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a hall pass or give me one?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck someone we both know or a complete stranger?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone way older or way younger?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone famous or someone rich?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone hot or someone good in bed?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone with a huge dick or amazing tongue?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone with a tight pussy or great head?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone dominant or submissive?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone kinky or vanilla?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone experienced or a virgin?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone rough or gentle?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex with someone freaky or normal?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be degraded during sex or worshipped?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be called a slut or a whore?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be treated like a princess or a toy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used for pleasure or for breeding?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a cum dump or a fuck doll?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be owned or be free?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a slave or a master?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be property or have property?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be collared 24/7 or only during sex?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be punished or rewarded?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be spanked or whipped?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be flogged or caned?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be paddled or belted?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be slapped or choked?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be bitten or scratched?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be marked or bruised?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have hickeys or bite marks?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have scratches or welts?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have bruises or rope burns?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be edged or overstimulated?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be denied orgasms or forced to cum?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have ruined orgasms or multiple orgasms?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather cum on command or not be allowed to cum?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather beg to cum or beg to stop?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be teased until you cry or fucked until you cry?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be tortured with pleasure or pain?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be fucked until you pass out or until you squirt?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be fucked until you scream or until you are silent?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be fucked until you break or until you submit?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be fucked in all your holes or just one repeatedly?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be double penetrated or triple penetrated?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be airtight or have all holes filled with toys?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be fisted or fucked with a huge toy?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be stretched or gaped?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be filled with cum or covered in cum?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather swallow cum or have it on your face?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have cum in your pussy or your ass?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have cum on your tits or your ass?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have cum in your mouth or your hair?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather taste cum or smell it?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather lick cum off yourself or someone else?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather snowball or creampie?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be bred or used as a cum dump?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be gangbanged or run a train?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather service a line of people or a circle?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be passed around or take turns?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used by 5 people or 10 people?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used by strangers or people you know?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used by men or women?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used by couples or singles?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used at a party or a club?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used in public or in private?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used while filmed or while people watch?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used for content or for pleasure?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be used for free or for money?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be pimped out or pimp someone out?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be sold or buy someone?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be rented or rent someone?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be auctioned or auction someone?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be traded or trade someone?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a hooker or a sugar baby?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be an escort or a stripper?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a cam girl or do onlyfans?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do porn or prostitution?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work at a brothel or a strip club?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work at a massage parlor or a dungeon?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work at a sex club or a glory hole?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work the streets or work online?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have a pimp or work independently?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have regulars or new clients?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do outcalls or incalls?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do short sessions or long sessions?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do vanilla or kinky sessions?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do solo or duo sessions?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do couples or singles?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do men or women clients?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do young or old clients?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do attractive or unattractive clients?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do rich or poor clients?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do famous or regular clients?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather charge by the hour or by the act?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather charge high prices or low prices?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather accept cash or cards?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather accept gifts or money?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work weekdays or weekends?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work days or nights?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work full time or part time?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work alone or with others?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather work from home or travel?', 'wild');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck everyone in this room or let everyone fuck me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch me get gangbanged or participate in one?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have me fuck your dad or your best friend?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck my mom or my sibling?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have an incest threesome or a family orgy?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck your cousin or your step sibling?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck your teacher or your boss?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck your doctor or your therapist?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck your priest or your lawyer?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a homeless person or a cop?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck someone with an STD or someone married?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck someone underage or someone elderly?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck someone disabled or someone dying?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck someone unconscious or someone drugged?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck someone against their will or be fucked against yours?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather rape or be raped?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather molest or be molested?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather abuse or be abused?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather torture or be tortured?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather kill during sex or die during sex?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a corpse or an animal?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather do necrophilia or bestiality?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a dog or a horse?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a pig or a sheep?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a chicken or a fish?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck roadkill or fresh kill?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck someone recently dead or long dead?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a zombie or a vampire?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a demon or an alien?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a monster or a ghost?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a robot or a doll?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck an object or a body part?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck food or furniture?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck a car or a building?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather fuck nature or technology?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex covered in blood or covered in shit?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have sex covered in piss or covered in vomit?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather eat shit or drink piss?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather lick an asshole or eat vomit?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather drink period blood or eat a used tampon?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather lick a toilet or a dumpster?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather eat garbage or roadkill?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather drink sewage or eat maggots?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be pissed on or shit on?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be vomited on or bled on?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be spit on or drooled on?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be cummed on by 100 people or pissed on by 10?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather drink a gallon of cum or a cup of piss?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather bathe in cum or in blood?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather swim in piss or in shit?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather drown in cum or in vomit?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be buried in shit or in corpses?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be covered in maggots or in leeches?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be covered in spiders or in snakes?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be covered in rats or in roaches?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be eaten alive by ants or by piranhas?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be burned alive or frozen alive?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be skinned alive or boiled alive?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be crucified or beheaded?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be hanged or shot?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be stabbed or beaten to death?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be drowned or suffocated?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be poisoned or strangled?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be electrocuted or gassed?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be tortured for days or killed instantly?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch me die or kill me yourself?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch your family die or die yourself?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather kill your family or kill yourself?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather kill a child or kill an elderly person?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather kill a stranger or someone you love?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather kill one person or let 10 people die?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather commit genocide or be genocided?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather start a war or end humanity?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather destroy the world or save it?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be Hitler or Stalin?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a Nazi or a terrorist?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a serial killer or a mass murderer?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a rapist or a pedophile?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a cannibal or a necrophile?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather eat human flesh or drink human blood?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather eat a baby or eat your own child?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather eat your parents or your siblings?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather eat me or let me eat you?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be eaten alive or watch someone be eaten?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be a victim or a perpetrator?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather suffer or cause suffering?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be in hell or send someone to hell?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be damned or damn someone else?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather sell your soul or take someone elses?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather make a deal with the devil or become the devil?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather go to hell or cease to exist?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be tortured for eternity or forgotten forever?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather live in agony or die in peace?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have everything or have nothing?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be god or be nothing?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather create life or destroy it?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather be immortal or mortal?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather live forever in pain or die now in peace?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch everyone you love die or die before them?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather lose all your memories or never make new ones?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather forget me or have me forget you?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather I never existed or you never existed?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather we never met or we met and lost each other?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather love me and lose me or never love at all?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather have me hate you or be indifferent to you?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather I cheat on you or leave you?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather I die loving you or live hating you?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather save me or save yourself?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather sacrifice me or sacrifice yourself?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather betray me or be betrayed by me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather hurt me or let me hurt you?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather break my heart or have yours broken?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather ruin me or be ruined by me?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather destroy me or watch me self destruct?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather save me from myself or let me fall?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather watch me suffer or end my suffering?', 'drunk');
INSERT INTO prompts (game_type, prompt_type, content, difficulty) VALUES ('would-you-rather', NULL, 'Would you rather let me live in pain or kill me mercifully?', 'drunk');
